spring:
  application:
    name: spring-security-oauth2
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lioGQI8HLpnFOAgb
            clientSecret: be5fc45eb1d33621432d4ca6dbee4faed17c27ed