spring:
  application:
    name: CLOUD-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: welcome-service
          uri: lb://WELCOME-API
          predicates:
            - Path=/welcome/**
        - id: greet-service
          uri: lb://GREET-API
          predicates:
            - Path=/greet/**
server:
  port: 3333