server:
  port: 3333

spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: greet-service
          uri: lb://GREET-API
          predicates:
            - Path=/greet/**
        - id: greet-service
          uri: lb://WELCOME-API 
          predicates:
            - Path=/welcome/**
    config:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost